### ISSUE TITLE
Design end-to-end wire-frames

### ISSUE THREAD

**Issue by niroshank** [the-elixir/web-app#13]

**Comment by ashan-perera** [comment]
![IMG_20191119_001541](https://user-images.githubusercontent.com/49959344/69498455-43392a00-0f0e-11ea-87fd-f9b0f7ab226f.jpg)
![IMG_20191119_001553](https://user-images.githubusercontent.com/49959344/69498456-43d1c080-0f0e-11ea-94d0-4b282378cd1b.jpg)
![IMG_20191119_231804](https://user-images.githubusercontent.com/49959344/69498458-446a5700-0f0e-11ea-98d6-6302521b91a7.jpg)
![IMG_20191119_231844](https://user-images.githubusercontent.com/49959344/69498459-446a5700-0f0e-11ea-84c7-b45b5ba78d36.jpg)
![IMG_20191119_231857](https://user-images.githubusercontent.com/49959344/69498460-446a5700-0f0e-11ea-85a1-4dc745537511.jpg)

**Comment by ashan-perera** [comment]
![IMG_20191119_001541](https://user-images.githubusercontent.com/49959344/69498606-a8d9e600-0f0f-11ea-8d9b-0709b37024a5.jpg)
![IMG_20191119_001553](https://user-images.githubusercontent.com/49959344/69498609-ae373080-0f0f-11ea-842e-deb710d56ab9.jpg)
![IMG_20191119_231844](https://user-images.githubusercontent.com/49959344/69498610-b1322100-0f0f-11ea-8d12-e84e221f6b28.jpg)
![IMG_20191119_231804](https://user-images.githubusercontent.com/49959344/69498611-b2634e00-0f0f-11ea-9803-4b23ebd0eae2.jpg)
![IMG_20191119_231857](https://user-images.githubusercontent.com/49959344/69498612-b42d1180-0f0f-11ea-93e1-d3a569c89af1.jpg)

**Comment by ashan-perera** [comment]
![IMG_20191119_001541](https://user-images.githubusercontent.com/49959344/69498765-89dc5380-0f11-11ea-9dd2-4484028f79ae.jpg)
![IMG_20191119_001553](https://user-images.githubusercontent.com/49959344/69498766-89dc5380-0f11-11ea-9f87-c6a4fb7f135d.jpg)
![IMG_20191124_231513](https://user-images.githubusercontent.com/49959344/69498767-8a74ea00-0f11-11ea-89a6-dd62630eb47d.jpg)
![IMG_20191124_231523](https://user-images.githubusercontent.com/49959344/69498768-8a74ea00-0f11-11ea-9c9d-329f0e3267dc.jpg)
![IMG_20191124_231535](https://user-images.githubusercontent.com/49959344/69498769-8a74ea00-0f11-11ea-95e9-95b9ae45e175.jpg)

**Comment by niroshank** [comment]
@ashan-perera can you create a 'Docs' folder in the root and upload the above snaps?

**Comment by niroshank** [comment]
done
